services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PW}

  backend:
    build:
      context: backend
      target: builder

    restart: always

    ports:
      - 8000:8000

    networks:
      - backnet
      - frontnet
    
    depends_on:
      db:
        condition: service_healthy

networks:
  backnet:
  frontnet:
